Update README.md
raeich/Test pull request #1
Opened 2021-09-14 04:41 UTC by raeich

2021-09-14 04:43 UTC, raeich commented
Hey @mfaade! Let me know what you think about these top 5.

2021-09-14 04:54 UTC, mjfaade10 requested changes

2021-09-14 04:54 UTC, mjfaade10 commented on README.md
> +Hey world, here is a list of my top 5 foods.
Hey! Can you change this to top 5 movies?

2021-09-15 04:06 UTC, raeich commented on README.md
> +Hey world, here is a list of my top 5 foods.
@mjfaade10 this has been updated!

2021-09-15 04:09 UTC, mjfaade10 approved these changes

2021-09-15 04:09 UTC, mjfaade10 commented on README.md
> +2. Superbad
Love this movie!

2021-09-15 04:09 UTC, mjfaade10 commented on README.md
> +3. 25th Hour
I haven't seen this one yet. Will have to check it out 💯

2021-09-17 16:25 UTC, merged